# Generated by Django 3.2 on 2021-04-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=32)),
                ('path_to_key', models.TextField(blank=True)),
                ('alarm_status', models.BooleanField(blank=True)),
            ],
        ),
    ]
