# Generated by Django 3.2 on 2021-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchatuser',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='botchatuser',
            name='surname',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
