# Generated by Django 3.2 on 2021-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210422_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchatuser',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('collegue', 'Collegue'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
