# Generated by Django 3.2 on 2021-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botchatuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botserver',
            name='path_to_key',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Key-File'),
        ),
        migrations.AlterField(
            model_name='botserver',
            name='ssh_key',
            field=models.TextField(blank=True, null=True, verbose_name='Key-Text'),
        ),
    ]
